### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by fpasch** [carla-simulator/ros-bridge#288]
### Porting Priorities
(from high to low; topic describes milestone, that can be reached when porting the nodes below)

#### Setup for manual driving

- [x]  [carla_ros_bridge](https://github.com/carla-simulator/ros-bridge/issues/277)
- [x] [carla_ego_vehicle](https://github.com/carla-simulator/ros-bridge/issues/276)
- [x] [carla_manual_control](https://github.com/carla-simulator/ros-bridge/issues/279)

Test: `roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch`

#### Automatically follow precalculated route

- [x] [carla_ad_agent](https://github.com/carla-simulator/ros-bridge/issues/274)

#### Automatically follow generated waypoints

- [x]  [carla_waypoint_publisher](https://github.com/carla-simulator/ros-bridge/issues/284)

#### Enable carla_ad_demo with rviz-plugin (execute scenarios, manual control, move camera)

- [x]  [carla_ros_scenario_runner](https://github.com/carla-simulator/ros-bridge/issues/280)
- [x]  [carla_spectator_camera](https://github.com/carla-simulator/ros-bridge/issues/281)
- [x] [carla_twist_to_control](https://github.com/carla-simulator/ros-bridge/issues/282)
- [x] [rviz_carla_plugin](https://github.com/carla-simulator/ros-bridge/issues/287)
- [x] [carla_ad_demo](https://github.com/carla-simulator/ros-bridge/issues/275)

#### Additional functionality
- [x] [carla_infrastructure](https://github.com/carla-simulator/ros-bridge/issues/278)
- [x] [carla_ackermann_control](https://github.com/carla-simulator/ros-bridge/issues/273)
- [x] [carla_walker_agent](https://github.com/carla-simulator/ros-bridge/issues/283)
- [x] [rqt_carla_plugin](https://github.com/carla-simulator/ros-bridge/issues/285)
- [x] [pcl_recorder](https://github.com/carla-simulator/ros-bridge/issues/286)

**Comment by ll7** [comment]
Will the ros1 and ros2 bridge be within the same repository?

**Comment by fpasch** [comment]
@ll7 Yes, that's the current plan. The ros2 branch is planned to become the new master (as it supports ros1 and ros2 in parallel)

**Comment by anand-bala** [comment]
Hey @fpasch, I know this issue is old but I was wondering if the `ros2` branch is usable (unstable is fine)?

**Comment by fpasch** [comment]
@anand-bala Yes. It should be pretty stable. (Testers are always welcome :-) )

**Comment by anand-bala** [comment]
Thanks! Looks like you have a tester now 😄
